### ISSUE TITLE
AxiosError: options must be an object

### ISSUE THREAD

**Issue by CKGrafico** [storyblok/storyblok-vue#171]
This is possibly related to https://github.com/storyblok/storyblok-nuxt/issues/210
When you start a new nuxt project its impossible to have it working.
The first error es that axios is not installed, after install it you will have that new error:
```
:
'AxiosError'
stack:
'AxiosError: options must be an object\n    at Object.assertOptions (file:///C:/Projects//NGO-HelpDev-Storyblok/node_modules/axios/lib/helpers/validator.js:67:11)\n    at Axios.request (file:///C:/Projects//NGO-HelpDev-Storyblok/node_modules/axios/lib/core/Axios.js:61:17)\n    at Axios.<computed> [as get] (file:///C:/Projects/l/NGO-HelpDev-Storyblok/node_modules/axios/lib/core/Axio…storyblok-vue.mjs:250:17)\n    at C:/Projects//NGO-HelpDev-Storyblok/node_modules/@storyblok/vue/dist/storyblok-vue.mjs:254:69\n    at new Promise (<anonymous>)\n    at X.i [as throttle] (C:/Projects//NGO-HelpDev-Storyblok/node_modules/@storyblok/vue/dist/storyblok-vue.mjs:253:12)\n    at C:/Projects//NGO-HelpDev-Storyblok/node_modules/@storyblok/vue/dist/storyblok-vue.mjs:532:28'
[[Prototype]]:
Error
```
![image](https://user-images.githubusercontent.com/2048511/196476599-5b5db38d-bba8-43bb-a744-8fb94a7c4df8.png)

As you can see seems that the real error comes from this package not nuxt package.

**Comment by aco228** [comment]
I am having the same issue:

```
code
: 
"ERR_BAD_OPTION_VALUE"
message
: 
"options must be an object"
name
: 
"AxiosError"
stack
: 
"AxiosError: options must be an object\n    at Object.assertOptions (https://127.0.0.1:5174/node_modules/.vite/deps/chunk-P6WNCWHP.js?v=61d1f5b8:1563:11)\n    at Axios.request (https://127.0.0.1:5174/node_modules/.vite/deps/chunk-P6WNCWHP.js?v=61d1f5b8:1615:25)\n    at Axios.<computed> [as get] (https://127.0.0.1:5174/node_modules/.vite/deps/chunk-P6WNCWHP.js?v=61d1f5b8:1692:17)\n    at Function.wrap [as get] (https://127.0.0.1:5174/node_modules/.vite/deps/chunk-P6WNCWHP.js?v=61d1f5b8:16:15)\n    at X.throttledRequest (https://127.0.0.1:5174/node_modules/.vite/deps/@storyblok_vue.js?v=88a8d76f:565:26)\n    at a (https://127.0.0.1:5174/node_modules/.vite/deps/@storyblok_vue.js?v=88a8d76f:268:17)\n    at https://127.0.0.1:5174/node_modules/.vite/deps/@storyblok_vue.js?v=88a8d76f:272:69\n    at new Promise (<anonymous>)\n    at X.i [as throttle] (https://127.0.0.1:5174/node_modules/.vite/deps/@storyblok_vue.js?v=88a8d76f:271:12)\n    at https://127.0.0.1:5174/node_modules/.vite/deps/@storyblok_vue.js?v=88a8d76f:552:28"
[[Prototype]]
: 
Error
```

on this piece of code from example:

```js
<script setup>

import { useStoryblok } from '@storyblok/vue';
const story = await useStoryblok('home', { version: 'draft' });

</script>
```

and this are packages I am using:

```
    "@storyblok/vue": "^6.3.2",
    "@vitejs/plugin-basic-ssl": "^0.1.2",
    "axios": "^1.1.3",
    "bootstrap": "^5.2.1",
    "pinia": "^2.0.21",
    "primeicons": "^5.0.0",
    "primevue": "^3.17.0",
    "vue": "^3.2.38",
    "vue-axios": "^3.4.1",
    "vue-router": "^4.1.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.0.3",
    "jsdom": "^20.0.0",
    "sass": "^1.55.0",
    "vite": "^3.0.9"
  }

```

**Comment by ralphjesy12** [comment]
same problem.

**Comment by patrykkurzeja91** [comment]
@CKGrafico Yeah, I just got [similar problem](https://github.com/storyblok/storyblok-nuxt/issues/211#issuecomment-1303160681) with `storyblok-nuxt`. It turns out to be axios as You wrote in Your update. Actually `axios@0.27.2` will do the trick!

Maybe it is a good time to update axios in storyblok?

**Comment by Dawntraoz** [comment]
Hi, folks @CKGrafico @patrykkurzeja91 @ralphjesy12 @aco228 👋
Sorry for the late reply. We were working on breaking changes.

Good news on this matter! We got rid of axios in the js-client, so now the @storyblok/vue SDK is updated with these changes in the last version, and the next one to be updated will be @storyblok/nuxt 🚀 Stay tuned and let us know if something pops up in the meantime 💜
